### ISSUE TITLE
Build Paths on Mac OS X

### ISSUE THREAD

**Issue by zmand97** [COx2/glslEditor_AudioPlugin#2]
I need to set up Build Paths for using this plugin, and I'm on a Mac OS X. However, I don't know where or what the build path(s) should connect to. Do you have any Build Path recommendations?

**Comment by COx2** [comment]
I'm not sure what exactly you mean by "Build Path", are you saying that you can't build this project?
The build settings for this project can be found in the GLSLPlugIn.jucer file. So, if you operate Projucer correctly, you can build this project on MacOS X.
