### ISSUE TITLE
Opening and running files on Mac

### ISSUE THREAD

**Issue by zmand97** [COx2/glslEditor_AudioPlugin#3]
Some files I'm opening and attempting to run on my MacBook (as opposed to Windows) are either not compatible, or seemingly not compatible, on Macs, or various errors pop up. I'll bullet the issues I'm dealing with in regards to the files just as a means of differentiating them:

-I can open the .jucer file in the .zip download for the plugin no problem on Mac, but the file labeled "Projucer.exe" generally cannot be opened on Macs. Is there a Mac equivalent of that file, or is the plugin's .jucer file exactly that?

-I tried running the DemoRunner file for the plugin, but it resulted in these errors and warnings, which I am attaching as screenshots. I don't know what they mean or how to fix them; I also don't know if these errors are contributing to the plugin not opening by itself or in an app like the ones listed in the README file, despite Xcode saying "Build Succeeded" after running it. Multiple message threads popped up in Xcode, and the error in red is the same in all threads; they're just on different lines in the code.

<img width="1132" alt="Screen Shot 2021-01-21 at 7 57 01 PM" src="https://user-images.githubusercontent.com/70781706/105431597-e6292900-5c23-11eb-8895-9ef98dc060da.png">
<img width="1131" alt="Screen Shot 2021-01-21 at 7 56 53 PM" src="https://user-images.githubusercontent.com/70781706/105431599-e6292900-5c23-11eb-9e8a-f36a6ce7206a.png">

**Comment by COx2** [comment]
> -I tried running the DemoRunner file for the plugin, but it resulted in these errors and warnings, which I am attaching as...

Well, you may want to contact the JUCE official for the issue related on the DemoRunner.

**Comment by COx2** [comment]
> -I can open the .jucer file in the .zip download for the plugin no problem on Mac, but the file labeled "Projucer.exe" generally cannot be opened on Macs. Is there a Mac equivalent of that file, or is the plugin's .jucer file exactly that?

"Projucer.exe" is executable file for Windows OS. I will add "Projucer.app" that is executable file for macOS.
