### ISSUE TITLE
Trouble having the plugin open when running it

### ISSUE THREAD

**Issue by zmand97** [COx2/glslEditor_AudioPlugin#4]
This issue is sort of a continuation of the previous issue that I brought up a while back. I seem to have taken care of the build paths, JUCE settings, etc. When running the Xcode project, it indicates "Build Succeeded." However, the plugin usually ends up either not opening, or buffering infinitely. I'm not entirely sure why.

**Comment by COx2** [comment]
Can you run the standalone version?

**Comment by COx2** [comment]
The Windows version is expected to run more stably.
If you have Windows, I recommend you to run the Windows version for testing.

**Comment by COx2** [comment]
If possible, could you please tell me the System information of your Mac machine (OS version, CPU, GPU, RAM, etc...)

Since Apple's recent stance is to abandon OpenGL, this project may already not work properly on some machines.

**Comment by zmand97** [comment]
I have a 2016 MacBook Pro, OS Big Sur version 11.1, with Intel Iris Graphics 540 1536 MB.

**Comment by COx2** [comment]
Oh, sorry.
I don't have test environment for BigSur with Intel CPU.

**Comment by COx2** [comment]
Hmm, I can run this project on my MacBook Pro(Big Sur with M1 CPU).

![image](https://user-images.githubusercontent.com/2960956/109985751-70e36480-7d48-11eb-8938-f18b34e4f29b.png)

By the way, I don't know the reason why GLSL doesn't work well like above on Apple Silicon.

**Comment by COx2** [comment]
By the way, it worked fine on another Mac machine.
2020 MacBook Pro, OS Catalina version 10.15.7, with Intel CPU

![image](https://user-images.githubusercontent.com/2960956/109990032-61661a80-7d4c-11eb-878a-4c140ab2fce4.png)

**Comment by COx2** [comment]
I can't be sure, but there is a possibility that Big Sur can't run it.

**Comment by zmand97** [comment]
So if I try another OS, then that might do the trick?

**Comment by COx2** [comment]
Let's give it a try.
By the way, I've never tried Linux.
